### ISSUE TITLE
Command not found Error

### ISSUE THREAD

**Issue by Sajid576** [esmog/nodexp#1]
<img width="439" alt="Capture" src="https://user-images.githubusercontent.com/36130772/107152326-85268280-6991-11eb-9f72-9e0520606e28.PNG">

Hello, whenever I try to run this command ,it gives me this error......can u tell me how to run this command?

**Comment by esmog** [comment]
Hi, seems that you have not installed python2.7.
Check the python versions that you have installed (if any) by hitting the command below:
`python -V`

**Comment by Sajid576** [comment]
cant I run this command with python3?

**Comment by esmog** [comment]
NodeXP needs **python2.7** in order to run.
Run the below command and make sure that the python2.7 version is installed:
`python2 -V`

**Comment by Sajid576** [comment]
<img width="461" alt="Capture" src="https://user-images.githubusercontent.com/36130772/107433807-10e80c80-6b54-11eb-9748-9fc2509bcf9b.PNG">

I am trying to run it with docker container.....bt looks lyk i need to import several modules.....is there any requirements.txt where I can list the importing modules?

**Comment by Sajid576** [comment]
after listing the modules name in the requirements.txt , I successfully ran this....thanx
